name: build
on:
  push:
    branches:
      - "sdmc-3909"

jobs:
  build-windows:
    runs-on: win-server2022-latest-8core
    steps:
      - name: Clean working directory
        shell: pwsh
        run: rm -r -fo *
        working-directory: .

      - name: Check out code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_TOKEN }}
          submodules: recursive

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Configure build system
        shell: pwsh
        run: cmake -S . -B build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -- /consoleloggerparameters:Nosummary
